GET http://localhost:3001/carrito
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpdGEiLCJpZCI6IjA3NGI0NGUyLTZiNDUtNGQ0OC1hYTZiLTI0NjU0Zjc3YTg4OSIsImlhdCI6MTcwMTYzNzIyMX0._pm8xGXQByp-f6Xrasyykq4MHrbfaSsipiV4V-VrSOc