GET http://localhost:3001/detail/9cc32b33-c558-4e91-be3b-6dc8c9371d8e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyYW5jbyIsImlkIjoiM2E3MDExMTQtODU1Yi00M2E4LTk4ZDQtOTM1YzBlNmZiNjI2IiwiaWF0IjoxNjk4MTMzOTc0fQ.LPdDU8OyDciPzCQVS-CeBXDnJrIfaaDOF0sD79BEg7s


