GET http://localhost:3001/carrito
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImYiLCJpZCI6IjE1YjM1ZmI0LTk4ZDUtNGI4NC1iY2U4LWRhNzRiNzE2ZjdjMSIsImlhdCI6MTcwNzA3NTk3MH0.WIGqHTzHjWP2ECC4C3c0HJOPjAzHvfE-UzqOkTScCDE