GET http://localhost:3001/carrito
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImYiLCJpZCI6IjRiYTM2MmM3LThhM2UtNGQ0Ni05YzcwLTcxYTE0ZGIxOWJmMSIsImlhdCI6MTcwNzE0NTY5N30.BtCG-yb8iEX5bbgzTFHq-7W8XSS3eHcXdMzMQMsQTSY